# Doni Maulana Syahputra
# Hari ke-1

## Eksplorasi Numpy
### Membuat Numpy

In [76]:
#Jawaban 1
import numpy as np

In [77]:
#Jawaban 2
my_array = np.array([100, 200, 300, 400, 500])
my_array

array([100, 200, 300, 400, 500])

In [78]:
#Jawaban 3
my_array_2 = np.arange(20, 80, 5)
my_array_2

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [79]:
#Jawaban 4
array_zero = np.zeros(5)
array_zero

array([0., 0., 0., 0., 0.])

In [80]:
#Jawaban 5
array_one = np.ones(5)
array_one

array([1., 1., 1., 1., 1.])

In [81]:
#Jawaban 6
array_random = np.random.rand(8)
array_random

array([0.07010844, 0.81614056, 0.90496851, 0.88794643, 0.50045173,
       0.04537632, 0.76125268, 0.09306861])

In [82]:
#Jawaban 7
array_integer = np.random.randint(10, 100, size = 8)
array_integer

array([29, 71, 42, 14, 77, 65, 70, 78])

### Shape, Reshape, Subsetting & Slicing

In [83]:
#Jawaban 1
print(my_array_2.shape)
print(my_array_2.size)
print(my_array_2.ndim)

(12,)
12
1


In [84]:
#Jawaban 2
my_2d_array = np.reshape(my_array_2,newshape = [3, 4])
my_2d_array

array([[20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

In [85]:
#Jawaban 3
my_2d_array[1:, 2]

array([50, 70])

In [86]:
#Jawaban 2
my_2d_array[2, 3]

75

### Array Operations

In [87]:
#Jawaban 1
array_sum = array_random + array_integer
array_sum

array([29.07010844, 71.81614056, 42.90496851, 14.88794643, 77.50045173,
       65.04537632, 70.76125268, 78.09306861])

In [88]:
#Jawaban 2
array_multi = 100 * array_random
array_multi

array([ 7.01084393, 81.61405619, 90.49685126, 88.79464335, 50.04517318,
        4.53763192, 76.12526759,  9.30686076])

In [89]:
#Jawaban 3
print(my_2d_array.min())
print(my_2d_array.max())
print(my_2d_array.mean())

20
75
47.5


## Eksplorasi Pandas

In [90]:
import pandas as pd

In [91]:
#Jawaban 1
fifa = pd.read_csv("FIFA_dirty_dataset.csv")
fifa

id                     name   rating  position   height    foot  \
0       1001             Gábor Király       69        GK      191   Right   
1     100143             Frederik Boi       65         M      184   Right   
2     100264          Tomasz Szewczuk       57         A      185   Right   
3     100325   Steeve Joseph-Reinette       63         D      180    Left   
4     100326             Kamel Chafni       72         M      181   Right   
...      ...                      ...      ...       ...      ...     ...   
8842    9801          Danijel Ljuboja       73         A      189    Left   
8843    9805            Craig Bellamy       79         A      175   Right   
8844    9807            Michel Breuer       68         D      183   Right   
8845    9815              Gill Swerts       65         D      179   Right   
8846    9913              Mehdi Nafti       69         M      179   Right   

       rare  pace  shooting  passing  dribbling  defending  heading  diving  \
0         0                                                              70   
1         0    61        65       63         59         62       62           
2         0    65        54       43         53         55       74           
3         0    68        38       51         46         64       71           
4         0    75        64       67         72         57       66           
...     ...   ...       ...      ...        ...        ...      ...     ...   
8842      1    62        73       64         74         56       68           
8843      0    80        78       67         81         62       71           
8844      0    61        40       56         51         70       74           
8845      0    65        48       63         65         67       69           
8846      0    55        56       64         65         69       60           

      handling  kicking  reflexes  speed   positioning  
0           66       63        74     35          66.0  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
...        ...      ...       ...    ...           ...  
8842                                               NaN  
8843                                               NaN  
8844                                               NaN  
8845                                               NaN  
8846                                               NaN  

[8847 rows x 19 columns]

In [92]:
#Jawaban 2
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8847 entries, 0 to 8846
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            8847 non-null   int64  
 1    name         8847 non-null   object 
 2    rating       8847 non-null   int64  
 3    position     8847 non-null   object 
 4    height       8847 non-null   int64  
 5    foot         8847 non-null   object 
 6    rare         8847 non-null   int64  
 7    pace         8847 non-null   object 
 8    shooting     8847 non-null   object 
 9    passing      8847 non-null   object 
 10   dribbling    8847 non-null   object 
 11   defending    8847 non-null   object 
 12   heading      8847 non-null   object 
 13   diving       8847 non-null   object 
 14   handling     8847 non-null   object 
 15   kicking      8847 non-null   object 
 16   reflexes     8847 non-null   object 
 17   speed        8847 non-null   object 
 18   positioning  930 non-null  

In [93]:
#Jawaban 2b
fifa.describe()

id       rating       height         rare   positioning
count    8847.000000  8847.000000  8847.000000  8847.000000    930.000000
mean   152337.538035    66.680457   181.750424     0.353114     64.955914
std     54506.606056     7.146679     6.454356     0.477965      8.854231
min         2.000000    40.000000   158.000000     0.000000     37.000000
25%    140001.500000    62.000000   178.000000     0.000000     59.000000
50%    171578.000000    66.000000   182.000000     0.000000     65.000000
75%    189185.000000    72.000000   186.000000     1.000000     71.000000
max    205583.000000    94.000000   208.000000     1.000000     91.000000

In [94]:
#Jawaban 3 
fifa.head()

id                     name   rating  position   height    foot   rare  \
0    1001             Gábor Király       69        GK      191   Right      0   
1  100143             Frederik Boi       65         M      184   Right      0   
2  100264          Tomasz Szewczuk       57         A      185   Right      0   
3  100325   Steeve Joseph-Reinette       63         D      180    Left      0   
4  100326             Kamel Chafni       72         M      181   Right      0   

   pace  shooting  passing  dribbling  defending  heading  diving  handling  \
0                                                              70        66   
1    61        65       63         59         62       62                     
2    65        54       43         53         55       74                     
3    68        38       51         46         64       71                     
4    75        64       67         72         57       66                     

   kicking  reflexes  speed   positioning  
0       63        74     35          66.0  
1                                     NaN  
2                                     NaN  
3                                     NaN  
4                                     NaN

In [95]:
#Jawaban 4
fifa.tail()

id              name   rating  position   height    foot   rare  pace  \
8842  9801   Danijel Ljuboja       73         A      189    Left      1    62   
8843  9805     Craig Bellamy       79         A      175   Right      0    80   
8844  9807     Michel Breuer       68         D      183   Right      0    61   
8845  9815       Gill Swerts       65         D      179   Right      0    65   
8846  9913       Mehdi Nafti       69         M      179   Right      0    55   

      shooting  passing  dribbling  defending  heading  diving  handling  \
8842        73       64         74         56       68                     
8843        78       67         81         62       71                     
8844        40       56         51         70       74                     
8845        48       63         65         67       69                     
8846        56       64         65         69       60                     

      kicking  reflexes  speed   positioning  
8842                                     NaN  
8843                                     NaN  
8844                                     NaN  
8845                                     NaN  
8846                                     NaN

In [96]:
#Jawaban 5
## a. Remove White Space dari seluruh nama columns
fifa.columns = [col.replace(" ", "") for col in fifa.columns]

In [97]:
## b. Remove white Space dari value pada columns
fifa['pace'] = fifa['pace'].str.lstrip()
fifa['shooting'] = fifa['shooting'].str.lstrip()
fifa['passing'] = fifa['passing'].str.lstrip()
fifa['dribbling'] = fifa['dribbling'].str.lstrip()

In [98]:
## c. Replace empty value
fifa['pace'] = fifa['pace'].replace("", np.nan)
fifa['shooting'] = fifa['shooting'].replace("", np.nan)
fifa['passing'] = fifa['passing'].replace("", np.nan)
fifa['dribbling'] = fifa['dribbling'].replace("", np.nan)

In [99]:
## d. Changing data type (object to float)
fifa['pace'] = fifa['pace'].astype(float)
fifa['shooting'] = fifa['shooting'].astype(float)
fifa['passing'] = fifa['passing'].astype(float)
fifa['dribbling'] = fifa['dribbling'].astype(float)

In [100]:
## No. 6
## a. Cek missing values
fifa.isna().sum()

id                0
name              0
rating            0
position          0
height            0
foot              0
rare              0
pace            930
shooting        930
passing         930
dribbling       930
defending         0
heading           0
diving            0
handling          0
kicking           0
reflexes          0
speed             0
positioning    7917
dtype: int64

In [101]:
## b. ganti missing values
mean_pace = round(fifa["pace"].mean())
fifa["pace"] = fifa["pace"].fillna(mean_pace)

mean_shoot = round(fifa["shooting"].mean())
fifa["shooting"] = fifa["shooting"].fillna(mean_shoot)

mean_pass = round(fifa["passing"].mean())
fifa["passing"] = fifa["passing"].fillna(mean_pass)

mean_drib = round(fifa["dribbling"].mean())
fifa["dribbling"] = fifa["dribbling"].fillna(mean_drib)

mean_pos = round(fifa["positioning"].mean())
fifa["positioning"] = fifa["positioning"].fillna(mean_pos)

In [102]:
# Nomor 7
fifa.query("rating == rating.max()")

id           name  rating position  height   foot  rare  pace  \
2195  158023   Lionel Messi      94        A     169   Left     1  93.0   

      shooting  passing  dribbling defending heading diving handling kicking  \
2195      87.0     82.0       97.0        46      67                           

     reflexes speed  positioning  
2195                        65.0

In [103]:
# Nomor 8
fifa.query("rating == rating.min()")

id          name  rating position  height    foot  rare  pace  \
7332  201094   Ben Garratt      40       GK     185   Right     0  68.0   

      shooting  passing  dribbling defending heading diving handling kicking  \
7332      55.0     59.0       61.0                       42       39      38   

     reflexes speed  positioning  
7332       43    49         42.0

In [104]:
# Nomor 9
average_height = fifa["height"].mean()
average_height

181.75042387249914

In [105]:
# Nomor 10
fifa.query("height > 181.7504238724")

id               name  rating position  height    foot  rare  pace  \
0       1001       Gábor Király      69       GK     191   Right     0  68.0   
1     100143       Frederik Boi      65        M     184   Right     0  61.0   
2     100264    Tomasz Szewczuk      57        A     185   Right     0  65.0   
5     100329     Abdoulaye Faye      72        D     187   Right     1  50.0   
8     100521        David Noble      64        M     183   Right     1  62.0   
...      ...                ...     ...      ...     ...     ...   ...   ...   
8837    9722   Nicolai Stokholm      67        M     182   Right     0  59.0   
8839    9751        Gábor Babos      71       GK     196   Right     1  68.0   
8840    9771   Orlando Engelaar      73        M     196    Left     1  38.0   
8842    9801    Danijel Ljuboja      73        A     189    Left     1  62.0   
8844    9807      Michel Breuer      68        D     183   Right     0  61.0   

      shooting  passing  dribbling defending heading diving handling kicking  \
0         55.0     59.0       61.0                       70       66      63   
1         65.0     63.0       59.0        62      62                           
2         54.0     43.0       53.0        55      74                           
5         37.0     47.0       43.0        76      82                           
8         52.0     66.0       65.0        56      53                           
...        ...      ...        ...       ...     ...    ...      ...     ...   
8837      67.0     71.0       56.0        70      70                           
8839      55.0     59.0       61.0                       70       70      60   
8840      71.0     71.0       65.0        75      61                           
8842      73.0     64.0       74.0        56      68                           
8844      40.0     56.0       51.0        70      74                           

     reflexes speed  positioning  
0          74    35         66.0  
1                           65.0  
2                           65.0  
5                           65.0  
8                           65.0  
...       ...   ...          ...  
8837                        65.0  
8839       70    29         75.0  
8840                        65.0  
8842                        65.0  
8844                        65.0  

[4634 rows x 19 columns]

In [106]:
# Nomor 11
fifa[fifa.duplicated("name", keep = False)]

id               name  rating position  height    foot  rare  pace  \
16    100670    Ashley Westwood      54        D     183   Right     0  47.0   
22    100756       Stephen Hunt      56        D     185    Left     0  67.0   
25    100798     James O'Connor      63        M     173   Right     0  61.0   
141   106019            Adriano      77        A     190    Left     0  62.0   
173    10764           Juanfran      71        D     182    Left     0  70.0   
...      ...                ...     ...      ...     ...     ...   ...   ...   
8519   52682               Nano      66        M     186    Left     0  74.0   
8544   53014   Fernando Navarro      75        D     178    Left     0  70.0   
8547   53021           Portillo      69        A     180    Left     0  66.0   
8656   53827     Matthew Taylor      74        M     178    Left     1  66.0   
8779     768             Felipe      70        D     178    Left     0  57.0   

      shooting  passing  dribbling defending heading diving handling kicking  \
16        26.0     39.0       40.0        62      57                           
22        32.0     46.0       46.0        59      63                           
25        53.0     61.0       60.0        68      70                           
141       80.0     52.0       71.0        59      67                           
173       52.0     67.0       63.0        75      64                           
...        ...      ...        ...       ...     ...    ...      ...     ...   
8519      56.0     66.0       67.0        63      45                           
8544      55.0     72.0       72.0        75      68                           
8547      72.0     54.0       69.0        44      57                           
8656      84.0     76.0       73.0        68      72                           
8779      47.0     64.0       56.0        70      71                           

     reflexes speed  positioning  
16                          65.0  
22                          65.0  
25                          65.0  
141                         65.0  
173                         65.0  
...       ...   ...          ...  
8519                        65.0  
8544                        65.0  
8547                        65.0  
8656                        65.0  
8779                        65.0  

[300 rows x 19 columns]

In [107]:
# Nomor 12
fifa.drop_duplicates("name", keep = "last")

id                     name  rating position  height    foot  rare  \
0       1001             Gábor Király      69       GK     191   Right     0   
1     100143             Frederik Boi      65        M     184   Right     0   
2     100264          Tomasz Szewczuk      57        A     185   Right     0   
3     100325   Steeve Joseph-Reinette      63        D     180    Left     0   
4     100326             Kamel Chafni      72        M     181   Right     0   
...      ...                      ...     ...      ...     ...     ...   ...   
8842    9801          Danijel Ljuboja      73        A     189    Left     1   
8843    9805            Craig Bellamy      79        A     175   Right     0   
8844    9807            Michel Breuer      68        D     183   Right     0   
8845    9815              Gill Swerts      65        D     179   Right     0   
8846    9913              Mehdi Nafti      69        M     179   Right     0   

      pace  shooting  passing  dribbling defending heading diving handling  \
0     68.0      55.0     59.0       61.0                       70       66   
1     61.0      65.0     63.0       59.0        62      62                   
2     65.0      54.0     43.0       53.0        55      74                   
3     68.0      38.0     51.0       46.0        64      71                   
4     75.0      64.0     67.0       72.0        57      66                   
...    ...       ...      ...        ...       ...     ...    ...      ...   
8842  62.0      73.0     64.0       74.0        56      68                   
8843  80.0      78.0     67.0       81.0        62      71                   
8844  61.0      40.0     56.0       51.0        70      74                   
8845  65.0      48.0     63.0       65.0        67      69                   
8846  55.0      56.0     64.0       65.0        69      60                   

     kicking reflexes speed  positioning  
0         63       74    35         66.0  
1                                   65.0  
2                                   65.0  
3                                   65.0  
4                                   65.0  
...      ...      ...   ...          ...  
8842                                65.0  
8843                                65.0  
8844                                65.0  
8845                                65.0  
8846                                65.0  

[8678 rows x 19 columns]